# Generated by Django 3.2.6 on 2021-08-27 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_img', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='timestamp',
        ),
    ]
