# Generated by Django 3.2.6 on 2021-08-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_img', '0002_remove_file_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.BooleanField(default=False)),
            ],
        ),
    ]
